# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

abstract_target 'Networking' do
    
     use_frameworks!
     
    pod 'Moya-ModelMapper'
    pod 'KeychainSwift', '~> 10.0'
    
    target 'Favorite TV Show'
    
    target 'Tv show app' do
 
    pod 'youtube-ios-player-helper'
    pod 'FSPagerView'
    pod 'IQKeyboardManagerSwift'
  # Pods for Tv show app
    end
end
